name: Setup

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: true
        default: '22.8.0'
        type: string

jobs:
  default:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Create node_modules Archive
        run: tar -czf node_modules.tar.gz node_modules

      - name: Upload node_modules Archive
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules.tar.gz